import json
import os
import time
from langgraph.prebuilt import create_react_agent
from langchain_core.tools import tool
from langchain.chat_models import init_chat_model
from weasyprint import HTML
from src.infrastructure.config import LLM_PROVIDER, QUERY_MODEL
from src.domain.prompts.teacher_prompt_en import TEACHER_PROMPT_EN

OUTPUT_DIR = "output/exams"


@tool("create_quiz")
def create_quiz(questions_json: str) -> str:
    """
    Validates and stores a multiple-choice quiz generated by the agent.

    The agent generates the quiz content directly. This tool receives the
    already-generated JSON, validates its structure, and returns it confirmed.

    Parameters:
        questions_json (str): A JSON string with the quiz questions. Must follow
                              this exact structure:
                              [
                                {
                                  "question": "Question text",
                                  "options": {"A": "...", "B": "...", "C": "...", "D": "..."},
                                  "answer": "B"
                                }
                              ]

    Returns:
        str: The validated JSON string, ready to be delivered to the user.

    Raises:
        ValueError: If the JSON is invalid or doesn't match the expected structure.
    """
    questions = json.loads(questions_json)
    required_keys = {"question", "options", "answer"}
    for q in questions:
        if not required_keys.issubset(q.keys()):
            raise ValueError(f"Question missing required keys: {q}")
        if set(q["options"].keys()) != {"A", "B", "C", "D"}:
            raise ValueError(f"Options must have exactly A, B, C, D: {q}")
        if q["answer"] not in {"A", "B", "C", "D"}:
            raise ValueError(f"Answer must be A, B, C, or D: {q}")
    return questions_json


@tool("create_exam")
def create_exam(html_content: str, filename: str) -> str:
    """
    Converts an HTML exam document to a PDF file using WeasyPrint.

    The agent generates the full HTML content directly following the exam
    design guidelines. This tool receives the HTML string, renders it to PDF,
    saves it to disk, and returns the file path.

    Parameters:
        html_content (str): A complete, valid HTML string ready for WeasyPrint.
                            Must include <!DOCTYPE html>, <meta charset="UTF-8">,
                            and @page CSS rules. No JavaScript, no viewport units,
                            no interactive form elements.

        filename (str): Descriptive name for the PDF, without extension.
                        Only ASCII letters, digits, and underscores — no spaces,
                        no accents, no special characters.
                        Example: "brecha_salarial_genero_examen"

    Returns:
        str: Path to the generated PDF file. Example: "output/exams/brecha_salarial_genero_examen.pdf"
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    output_path = os.path.join(OUTPUT_DIR, f"{filename}.pdf")
    HTML(string=html_content).write_pdf(output_path)
    return output_path


def get_teacher_agent():
    llm = init_chat_model(model_provider=LLM_PROVIDER, model=QUERY_MODEL)
    teacher_agent = create_react_agent(
        model=llm,
        tools=[create_quiz, create_exam],
        prompt=TEACHER_PROMPT_EN,
    )
    return teacher_agent
