import asyncio
import json

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from langchain_core.messages import HumanMessage
from sqlmodel import Session, select

from src.api.dependencies import get_checkpointer, get_graph
from src.api.schemas import ChatStreamRequest
from src.api.streaming import SSEEvent, format_sse, SSEAgentTracer, run_graph_with_sse, GraphExecutionError
from src.application.graph.helpers import playlist_exist
from src.application.graph.state import State
from src.application.services.memory_manager import MemoryManager
from src.domain.models import Playlist
from src.infrastructure.config import ENGINE, ENGINE_SESSION_KWARGS

router = APIRouter(prefix="/chat", tags=["chat"])


def _get_playlist_metadata(playlist_id: str) -> dict:
    with Session(ENGINE, **ENGINE_SESSION_KWARGS) as session:
        playlist = session.exec(
            select(Playlist).where(Playlist.playlist_id == playlist_id)
        ).first()
    if not playlist:
        return {"title": "", "author": "", "description": ""}
    return {
        "title": playlist.title,
        "author": playlist.author,
        "description": playlist.description,
    }


@router.post(
    "/stream",
    summary="Stream a chat response",
    description=(
        "Sends a message to the multi-agent system and streams the response as Server-Sent Events (SSE). "
        "The agent pipeline emits real-time progress events before the final answer: tool calls, "
        "retrieval observations, quiz/PDF artifacts, and source citations.\n\n"
        "**SSE event types emitted (in order):**\n"
        "- `status_update` — agent lifecycle and tool call progress (start/end with preview)\n"
        "- `artifact_quiz` — multiple-choice quiz generated by the teacher agent\n"
        "- `artifact_pdf` — exam PDF ready for download\n"
        "- `citations` — video timestamps that sourced the response\n"
        "- `final_response` — the agent's final text answer\n"
        "- `error` — emitted instead of `final_response` if the graph or stream fails\n\n"
        "**Headers returned:**\n"
        "- `X-Chat-Id` — UUID of the session (new or existing).\n"
        "- `X-Accel-Buffering: no` — disables nginx proxy buffering for real-time delivery.\n\n"
        "**Session handling:** if `chat_id` is omitted, the server generates a new UUID and returns it "
        "in `X-Chat-Id`. Pass it back in subsequent requests to continue the same conversation."
    ),
    response_description="SSE stream of agent events. Content-Type: text/event-stream.",
    responses={
        200: {
            "description": "SSE stream opened successfully.",
            "content": {
                "text/event-stream": {
                    "example": (
                        "event: status_update\n"
                        'data: {"agent": "agent_analyst", "phase": "start"}\n\n'
                        "event: status_update\n"
                        'data: {"tool": "chunks_from_query", "phase": "start", "preview": "what is backpropagation"}\n\n'
                        "event: status_update\n"
                        'data: {"tool": "chunks_from_query", "phase": "end", "preview": "[{\\"page_content\\": \\"...\\"}]"}\n\n'
                        "event: citations\n"
                        'data: {"items": [{"video_id": "dQw4w9WgXcQ", "start_seconds": 142, "label": "Neural Networks - Lecture 3"}]}\n\n'
                        "event: final_response\n"
                        'data: {"content": "Backpropagation is an algorithm for computing gradients..."}\n\n'
                    )
                }
            },
        },
        500: {"description": "Failed to create the chat session in the database."},
    },
)
async def chat_stream(
    body: ChatStreamRequest,
    graph=Depends(get_graph),
    checkpointer=Depends(get_checkpointer),
):
    playlist_id = body.playlist_id

    memory = MemoryManager(
        checkpointer=checkpointer,
        chat_id=body.chat_id,
        playlist_id=playlist_id,
    )
    chat_id = memory.get_chat_id()
    chat_db_id = memory.chat_instance.id

    if chat_db_id is None:
        raise HTTPException(status_code=500, detail="Failed to create chat session")

    context = await memory.get_context()
    playlist_metadata = _get_playlist_metadata(playlist_id)

    state: State = {
        "messages": [HumanMessage(content=body.message)],
        "query": body.message,
        "playlist_id": playlist_id,
        "context": context,
        "playlist_metadata": playlist_metadata,
    }

    queue: asyncio.Queue = asyncio.Queue()
    tracer = SSEAgentTracer(queue=queue, chat_db_id=chat_db_id)
    config = {
        "configurable": {"thread_id": chat_id},
        "callbacks": [tracer],
    }

    async def event_stream():
        try:
            async for chunk in run_graph_with_sse(graph, state, config, queue, chat_db_id):
                yield chunk
            await memory.update_chat()
        except GraphExecutionError as e:
            yield format_sse(SSEEvent("error", {"message": str(e), "code": "GRAPH_ERROR"}))
        except Exception as e:
            yield format_sse(SSEEvent("error", {"message": str(e), "code": "STREAM_ERROR"}))

    headers = {
        "X-Chat-Id": chat_id,
        "X-Accel-Buffering": "no",
        "Cache-Control": "no-cache",
    }
    return StreamingResponse(event_stream(), media_type="text/event-stream", headers=headers)
