from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

router = APIRouter(prefix="/files", tags=["files"])

_EXAMS_DIR = Path("output/exams")


@router.get(
    "/exams/{filename}",
    summary="Download a generated exam PDF",
    description=(
        "Serves a PDF exam file generated by the teacher agent. "
        "The `url` field in every `artifact_pdf` SSE event and `ArtifactResponse` points here. "
        "Only `.pdf` files are served — any other extension returns 400. "
        "The filename is sanitized server-side to prevent path traversal."
    ),
    response_description="Binary PDF file.",
    responses={
        200: {"description": "PDF file.", "content": {"application/pdf": {}}},
        400: {"description": "Filename does not end in `.pdf`."},
        404: {"description": "File not found on disk."},
    },
)
def download_exam(filename: str):
    safe_name = Path(filename).name
    if not safe_name.endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are served")

    file_path = _EXAMS_DIR / safe_name
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="File not found")

    return FileResponse(path=str(file_path), media_type="application/pdf", filename=safe_name)
