from datetime import datetime
from typing import Literal
from pydantic import BaseModel, Field


class VideoSummary(BaseModel):
    video_id: str = Field(description="YouTube video ID (11-character string).")
    title: str = Field(description="Video title as returned by the YouTube Data API.")
    thumbnail_url: str = Field(description="URL of the video thumbnail image.")
    duration_seconds: int = Field(description="Total video duration in seconds.")


class PlaylistResponse(BaseModel):
    playlist_id: str = Field(description="YouTube playlist ID.")
    title: str = Field(description="Playlist title.")
    author: str = Field(description="Channel name that published the playlist.")
    description: str = Field(description="Playlist description.")
    thumbnail_url: str = Field(description="URL of the playlist thumbnail image.")
    videos_qty: int = Field(description="Total number of videos in the playlist.")
    videos: list[VideoSummary] = Field(description="Ordered list of videos (by playlist position).")
    status: Literal["ready", "indexing", "error"] = Field(
        description=(
            "`indexing` — transcripts are being loaded into the vector store (background task running). "
            "`ready` — fully indexed, available for chat. "
            "`error` — ingestion failed."
        )
    )


class ChatMessage(BaseModel):
    role: Literal["human", "ai"] = Field(description="Message author: `human` for user turns, `ai` for agent responses.")
    content: str = Field(description="Plain-text message content.")


class ChatHistoryResponse(BaseModel):
    chat_id: str = Field(description="UUID of the chat session.")
    messages: list[ChatMessage] = Field(
        description="Last 6 messages from the active LangGraph checkpoint (the sliding window kept in memory)."
    )
    summary: str | None = Field(
        description=(
            "Rolling summary of older messages that were compressed out of the active window. "
            "Null if the conversation has not yet exceeded the 6-message threshold."
        )
    )


class ArtifactResponse(BaseModel):
    artifact_id: str = Field(description="UUID that uniquely identifies this artifact.")
    type: Literal["quiz", "citations", "pdf"] = Field(
        description=(
            "`quiz` — multiple-choice quiz generated by the teacher agent. "
            "`citations` — list of video timestamps that sourced the last response. "
            "`pdf` — exam PDF file generated by the teacher agent."
        )
    )
    data: dict | list = Field(
        description=(
            "Artifact payload. Shape depends on type: "
            "quiz → `{quiz: [{question, options: {A,B,C,D}, answer}]}` | "
            "citations → `{items: [{video_id, start_seconds, label}]}` | "
            "pdf → `{filename, url}`."
        )
    )
    filename: str | None = Field(description="PDF filename. Only present when type is `pdf`, null otherwise.")
    created_at: datetime = Field(description="UTC timestamp of artifact creation.")
